osbuild/image-builder-cli

LICENSE

Provide the common license (Apache) that is used for Image Builder projects.

chore: LICENSE

---

README.md

Add the common blurb(s) that are on all Image Builder project READMEs.

chore: README blurbs

---

.github/workflows/release.yml

Using staging branch for now, due to the new
release_artifacts.

github/workflows: introduce release action

---

.github/workflows/create-tag.yml

Helper to create a tag for a new release.

github/workflows/create-tag: initial version

---

.github/workflows/release.yml

Enable creating release artifacts

github/workflows/release.yml: enable creating release artifacts

---

.github/workflows/pr_best_practices.yml

This commit adds the pr-best-practices check, which prevents pull requests without descriptions being merged and which allows developers to quickly create Jira Tasks based on the /jira-epic command in pull request descriptions or comments.

actions: Add pr-best-practices workflow (HMS-5161)

---

.packit.yaml
Makefile

Avoid duplicate implementation of "version"

Makefile/packit: avoid duplicate implementation of "version"

---

README.md

This commit adds an example for how to pass the blueprint and what content the blueprint should have.

README: add blueprint example

---

.github/workflows/pytest.yaml
.pre-commit-config.yaml

pre-commit: re-enable golangci-lint

---

.spellcheck-en-custom.txt
doc/00-installation.md
doc/01-usage.md
doc/10-faq.md

work in progress
---
based on #138

more doc updates

---

doc/01-usage.md

Very minor one character fix to unblock https://github.com/osbuild/osbuild.github.io/pull/151

doc: fix typo

---

README.md

Document how cross building works.

README: document that cross building works

---

.spellcheck-en-custom.txt
README.md
doc/01-usage.md

I'm doing another pass over the documentation, draft until I feel I've added enough for this to be useful.

doc: updates

---

go.mod
go.sum
image-builder.spec

Some important PRs have landed there, I'd like to do an extra release to push these out:
1. Change branched/rawhide for Fedora.
2. AlmaLinux definitions.

deps: bump images

---

.spellcheck-en-custom.txt
README.md

I will add more info about Satellite once there is a CLI release with the patch and I find time to test it:
https://github.com/osbuild/images/pull/1414
SSIA

docs: subscription basic info

---

Makefile
cmd/image-builder/main.go
cmd/image-builder/version.go
test/test_container.py

Conditionally include the git commit for the build if no `BuildVersion` was set explicitly.
---
See: #227. This is a proof of concept as I'm not entirely sure what idioms and behaviors I like.

main: `--version` includes git commit

---

image-builder.spec

This got out of sync, somehow?

spec: fix up version number

---

cmd/image-builder/main_test.go
cmd/image-builder/repos.go

This commit fixes the issue that --extra-repo are not added correctly to the repo registry when doing cross arch building. The issue is that they get added early at the reporegistry level and because we don't know yet what arch will be used it was initially only added to the host arch. This was fine before we supported cross-arch building.
But now that we do support cross-arch building this is of course an issue and produces subtle bugs. This commit is the "easy" fix, the extra repos are just added to for all architectures. This may not be right but because they are optional its the reponsibility of the user to provide the right ones. Eventually we should probably be smarter here and move extra repo support into manifestgen but that requires changes in images and an images release so this …

main: fix --extra-repos support when cross building

---

.spellcheck-en-custom.txt
doc/00-installation.md
doc/01-usage.md
doc/10-faq.md
doc/20-build-systems.md

Going to do another pass on our documentation; draft until I'm done.

doc: many updates (HMS-6127)

---

cmd/image-builder/main_test.go
go.mod
go.sum

SSIA
/jira-epic HMS-8910
JIRA: [HMS-9366](https://issues.redhat.com/browse/HMS-9366)

go.mod: update osbuild/images to 0.190.0 (dnfjson -> depsolvednf rename) (HMS-9366)

---

README.md
doc/00-installation.md

Since we're available in CentOS let's mention that.

doc: mention CentOS
