osbuild/image-builder-cli

README.md

This commit adds some examples and how to use to the README.

README: document install, prerequists and list-images

---

cmd/image-builder/main.go
cmd/image-builder/main_test.go

Tiny commit to error if extra arguments are passed to list-images. Only `--filter` is supported there currently.

main: list-images takes no args (just --filter)

---

.github/workflows/go.yml
HACKING.md
cmd/image-builder/distro.go
cmd/image-builder/distro_test.go
cmd/image-builder/export_test.go
cmd/image-builder/filters.go
cmd/image-builder/filters_test.go
cmd/image-builder/list.go
cmd/image-builder/main.go
cmd/image-builder/main_test.go
go.mod
internal/blueprintload/blueprintload.go
internal/blueprintload/blueprintload_test.go
internal/manifestgen/manifestgen.go
internal/manifestgen/manifestgen_test.go
internal/manifesttest/manifesttest.go
internal/manifesttest/manifesttest_test.go

This commit implements the `manifest` command for `image-builder`.
It will generate an osbuild manifest based on the given inputs,
e.g.:
```console
$ ./image-builder manifest --blueprint /path/to/blueprint.toml centos-9 qcow2
{"version":"2","pipelines":[{"name":"build","runner":",...
```
Note that there is an integration test but because of the depsolve
it will be slow. It will be skipped when doing `go test -short`.
Integration tests for ostree commit, this is because  ostree commit integration tests will need "build" first because the way this is tested today is that first an edge-commit is created, then an edge-ami based on this commit is generated. But "build" is currently missing
Note that this has no README.md update for `manifest` because manifest is considered an internal command, …

cmd: implement manifest command

---

README.md
cmd/image-builder/build.go
cmd/image-builder/main.go
cmd/image-builder/main_test.go
cmd/image-builder/manifest.go
internal/testutil/testutil.go
internal/testutil/testutil_test.go

This commit adds the `build` command. It takes the same flags as
`manifest` and will build the specified image.
E.g.
```console
$ image-builder-cli build --distro centos-9 qcow2
...
```

cmd: add new `build` command

---

.github/workflows/container.yaml
.github/workflows/go.yml
.github/workflows/pytest.yml
.github/workflows/testdeps.yml
Containerfile
README.md
cmd/image-builder/build.go
cmd/image-builder/main.go
cmd/image-builder/main_test.go
entrypoint.sh
internal/manifestgen/manifestgen.go
test/containerbuild.py
test/test_container.py

This PR adds Containerfile integration, with that a bib style deploy/run is possible. The Containerfile is pretty nasty right now, especially around the "getting supported repositories" part. This needs to get fixed either in composer or images IMHO (or via go:embed). But with that we can give it to our early users and let them play with building images.
It also contains automatic container building as part of the GH action (thanks @supakeen!) and once we have it we can update the README to point to the auto-generated containers for even easier testing/using.
As is "list-images" and "manifest" will work but once #8 is merged the below works (on my local system, we want tests here :)
Run build via container, bib-style:
```console
$ sudo podman build . -t test-icbli
$ sudo podman run …
```

misc: add Containerfile

---

Containerfile
cmd/image-builder/main.go
entrypoint.sh

This commit follows a suggestion from Ondrej to add a better default for `--store`: /var/cache/image-builder/store.
This is nice as it will give users automatic caching and makes the container also nicer.

ibcli: use `/var/cache/image-builder/store` as default for `--store`

---

.github/workflows/go.yaml
.github/workflows/pytest.yaml

This commit adds the missing `merge_group` to the pytest and go test workflows.
Note that I added `types: [ "checks_requested" ]` (just like we have for the container.yaml) but I'm not actually sure about it, the GH docs are a bit unclear to me here, it seems they suggest to keep this generic but then the example explicitly uses `type` (I'm probably overthinking this fwiw).
[1] https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#merge_group

workflow: run tests as part of the merge group

---

.github/workflows/container.yaml

The promised followup for #11. Also builds `aarch64` containers; note that this is slow hence it wasn't in the initial commit.

ci: enable aarch64 container builds

---

.github/dependabot.yml
.gitignore
.packit.yaml
Makefile
image-builder-cli.spec
tools/rpm_spec_add_provides_bundle.sh
tools/rpm_spec_vendor2provides

This is a maybe controversial version of #14 which tries to avoid commiting `vendor/` but patching source tar ball.
Prerequisite to testing https://github.com/osbuild/release-action/pull/25

package: specfile

---

.github/workflows/container.yaml
.github/workflows/create-tag.yml
.github/workflows/go.yaml
.github/workflows/pr_best_practices.yml
.github/workflows/pytest.yaml
.github/workflows/release.yml
.github/workflows/testdeps.yaml
.gitignore
.golangci.yml
.packit.yaml
.pre-commit-config.yaml
.pylintrc
.spellcheck-en-custom.txt
.spellcheck.yml
.yamllint
HACKING.md
Makefile
README.md
setup.cfg
test/.pylintrc
test/containerbuild.py
test/test_container.py
tools/.pylintrc

Introduce pre-commit linting with `make lint`.
Also add this to github actions.

Introduce pre-commit / `make lint`

---

go.mod
go.sum
internal/manifestgen/manifestgen.go

This moves to the new images Manifest() API from PR#1107.

manifestgen: port to the new `images` manifest seed

---

Makefile

For releases this does not change anything, as the version in the spec file is the same as the git tag. For
intermediate/tainted versions packer seems to patch the spec file to the version given in `.packit.yaml`
(which is the latest git-tag), then the filename and version would be inconsistent.
Rationale for this change was, that the packit build failed, as the version was set "4" but the source-tar-ball version was "5" from the spec file.

Makefile: fix Packit version by using git tag

---

internal/manifestgen/manifestgen.go

When depsolve is run it returns a list of packageSpecs and the matching repository config. This repo config is different/distinct from the repository config that is passed into depsolve via the package sets or the repositories that are loaded via the reporegistry and needs to be passed into `manifest.Serialize()`.
The key different is that the depsovle `repoConfig` contains the repo.Id that match the packageSpec.RepoId. With those two matching IDs we can use librepo (see osbuild PR#1974) to infere what mirror to use for what package.
This commit now passes the correct repoConfig into preManifest.Serialize() now.
No test (sorry!) as this is really hard to test in isolation, there is nothing observable today from repoConfig and it is impossible to add a "witness" pipelien that could check …

manifestgen: pass missing repoConfig to preManifest.Serialize()

---

.spellcheck.yml

Pyspelling does not seem to read `.gitignore` file, so we'll manually exclude it for now.
fixes #62

spellcheck: ignore release_artifacts directory

---

README.md
cmd/image-builder/main.go
cmd/image-builder/main_test.go

Changes the blueprint argument to a named argument after some discussion outside of GitHub. This allows for passing multiple image types later on and slightly simplifies the case of not passing a blueprint.
See #31.
/jira-epic COMPOSER-2418
JIRA: [HMS-5340](https://issues.redhat.com/browse/HMS-5340)

`--blueprint` (HMS-5340)

---

cmd/image-builder/main.go

Fixes up the usage strings and argument counts for the build and manifest subcommands after we moved to `--blueprint`.

fix up usage of cmd

---

image-builder-cli.spec

We can't build images without having osbuild installed.

spec: require osbuild

---

cmd/image-builder/main.go
cmd/image-builder/main_test.go
cmd/image-builder/manifest.go
go.mod
go.sum
image-builder-cli.spec
internal/manifestgen/manifestgen.go
internal/manifestgen/manifestgen_test.go
test/test_container.py

With that it then adds a new `--use-librepo` switch that will
enable librepo based downloading so that people can use
the new backend.
It is on by default currently, the risk is that it got no real testing
with secrets (but there code is there and similar to what curl
is doing) but the upside is that it will help with the centos/fedora
cases as there the mirror retry feature is import important.

main: add `--use-librepo` to support librepo  downloads

---

.spellcheck-en-custom.txt
README.md
cmd/image-builder/build.go
cmd/image-builder/main.go
cmd/image-builder/main_test.go
cmd/image-builder/manifest.go
internal/manifestgen/manifestgen.go
internal/manifestgen/manifestgen_test.go
test/test_container.py

This commit adds an option to generate an sbom file via the
new `--export-sbom`option.
This to follows https://github.com/osbuild/osbuild-composer/pull/4359 and names the isboms `<image_filename>.<pipeline_purpose>-<pipeline_name>.spdx.json`
Once that is in we can do `--extra-artifacts=manifest` (this should be much simpler) and maybe later `extra-artifacts=buildlog`.
Closes: https://github.com/osbuild/image-builder-cli/issues/46
JIRA: RHELBU-3011

ibcli: add new --extra-artifacts option that can write an sbom file

---

cmd/image-builder/distro.go
cmd/image-builder/distro_test.go

Fixes this:
```
€ go run ./cmd/image-builder build fedora-minimal
No distro name specified, selecting "fedora-41" based on host, use --distro to overrideerror: cannot find image for: distro:"fedora-41" type:"fedora-minimal" arch:"x86_64"
```
to this:
```
€ go run ./cmd/image-builder build fedora-minimal
No distro name specified, selecting "fedora-41" based on host, use --distro to override
error: cannot find image for: distro:"fedora-41" type:"fedora-minimal" arch:"x86_64"
```

image-builder: newline in error message

---

.packit.yaml
HACKING.md
Makefile
README.md
image-builder.spec
test/conftest.py
tools/rpm_spec_add_provides_bundle.sh

`image-builder` will be the main entrypoint into the Image Builder stack. We will rename the repositories later on; but let's start referring to it in its new official name.

spec: rename to `image-builder`

---

README.md
cmd/image-builder/build.go
cmd/image-builder/main.go
cmd/image-builder/main_test.go
cmd/image-builder/manifest.go

This commit adds support for `--extra-artifacts=manifest`. If
that is given as part of the build an extra artifacts called
`<img-name>.osbuild-manifest.json` will be created in the
output directory.
Closes: https://github.com/osbuild/image-builder-cli/issues/42

main: add `--extra-artifacts=manifest`

---

README.md
cmd/image-builder/main.go
cmd/image-builder/main_test.go
cmd/image-builder/manifest.go
test/test_container.py

This PR, after some discussion with @achilleas-k, @schuellerf, and @mvo5 to rename some arguments.
This PR:
1. Renames `--store` to `--cache` (#77).
2. Renames the `--extra-artifacts`

renaming arguments

---

.packit.yaml
go-vendor-tools.toml
image-builder.spec

Use go-vendor-tools to generate the license identifiers for our vendored code. This initial commit does not yet apply the rest of go-vendor-tools abilities to manage the vendoring itself.
There will be more followup work required to enable the `go-vendor-tools` macros but this first step lists all licenses from vendored code.

spec: use go-vendor-tools to generate license

---

go.mod
go.sum

Update images to understand the `main` of `osbuild` that we integration test against.
After the package has landed in Fedora (see #88) I'll be updating the specfile to also use the dnf-json API version.

deps: update `images`

---

.github/workflows/go.yaml

Running the tests inside fedora means we get much more meaningful results as we will have all the required packaes and there will be no need to skip tests.

github: run tests inside a fedora container

---

cmd/image-builder/main_test.go

This commit puts the build argument tests into a single table to cosolidate them a bit.
(tiny cleanup)

test: consolidate the `build` argument tests into a single table

---

test/test_container.py

For some reason on a bunch of my systems `platform.processor()` always returns an empty string. `platform.machine()` consistently works on those systems.
This closes #95.

test: switch to `platform.machine`

---

cmd/image-builder/main.go

I also added Fedora, why not. :)

cmd/image-builder: fix typos in cobra descs

---

README.md

This commit adds a small FAQ entry to explain the relation between `bib` and `ibcli`.
Thanks to Jonathan Lebon for the suggesiton.
Closes: https://github.com/osbuild/image-builder-cli/issues/89

README: add FAQ about relation between `bib` and `ibcli`

---

image-builder.spec

Changes as pointed out in the [Fedora package review](https://bugzilla.redhat.com/show_bug.cgi?id=2339108).

specfile: fedora review changes

---

cmd/image-builder/build.go
cmd/image-builder/manifest.go
test/test_container.py

Create the output directory; this is a no-op if it already exists but fixes #94 if it doesn't. The code is similar to (but not identical to) the checks done in `cmd/image-builder/manifest.go` for the `withSBOM` parts.
We might (or I) might want to consolidate those two codepaths either here in a followup.

image-builder: create directory

---

cmd/image-builder/build.go
cmd/image-builder/main.go
cmd/image-builder/main_test.go
go.mod
go.sum
internal/testutil/testutil.go
internal/testutil/testutil_test.go
test/conftest.py
test/test_container.py

[draft as this lacks tests,  not easy to do right now without duplicating code from bib, looking into this]
This commit add progress reporting similar to what `bib` is doing.
It imports the progress from `bootc-image-builder` for now. There
is an open PR for moving this to images but there are some
concerns about moving it there so for now we just use bib.
This is not too bad because eventually bib and ibcli will merge.

main: add --progres (similar to bib)

---

Containerfile

This commit changes the build to not build with CGO. There is really no need to build with CGO, we only need it for the `crypt()` version in the images library. However since with the merge of https://github.com/osbuild/images/pull/1114
that is no longer an issue.

Containerfile: build without CGO to avoid arm64 crashing

---

cmd/image-builder/main.go

This commit tweaks the help output for the manifest and build commands to make clear that only the image type is a required argument but the rest can be overriden via extra flags.
Thanks to Achilleas for noticing.

main: tweak the help of `manifest` and `build`

---

cmd/image-builder/main.go

This commit silences logrus logging for now by just dicarding everything from it. The rational is that the underlying libraries produce a lot of output, e.g. every build currently results in
```console
$ image-builder build qcow2
WARN[0000] Failed to load consumer certs: no consumer key found
...
```
which is confusing to our users. What is worse is that containers also uses logrus so we can get random warnings without context from there too. Until we have a way to filter log messages this seems to be the most practical way.
We can add `--verbose` or `--debug` later to enable these kinds of messages.

main: silence all logrus logging for now

---

.spellcheck-en-custom.txt
README.md
doc/00-installation.md
doc/01-usage.md
doc/10-faq.md
doc/index.md

Let's have some tiny initial docs; to be expanded later.

Initial Documentation

---

cmd/image-builder/describeimg.go
cmd/image-builder/describeimg_test.go
cmd/image-builder/export_test.go
cmd/image-builder/main.go
cmd/image-builder/main_test.go

[While this should follow https://github.com/osbuild/images/pull/1104, i.e. this output should be used as input in https://github.com/osbuild/images/pull/1104 we could still make it available as an unstable feature?]
This commit adds a new `describe-image` comamnd that contains
the details about the given image type. The output is yaml as
it is both nicely human readable and also machine readable.
The output looks like this:
```yaml
$ ./image-builder describe-image rhel-9.1 tar
@WARNING - the output format is not stable yet and may change
distro: rhel-9.1
type: tar
arch: x86_64
os_vesion: "9.1"
bootmode: none
partition_type: ""
default_filename: root.tar.xz
packages:
include:
- policycoreutils
- selinux-policy-targeted
- selinux-policy-targeted
exclude:
- rng-tools
```
Thanks to Ondrej …

cmd: add new `describe-image` command

---

.packit.yaml

Enable automatic builds and PR creation in Fedora since `image-builder` has landed there.

ci/packit: enable fedora PRs

---

image-builder.spec

We received a commit downstream by Björn Esser. After asking around for the reasoning behind the commit it seems that we're likely assuming that this package is available in the buildroot.
Let's depend on it explicitly instead of assuming it is there.

specfile: build requires `libxcrypt-compat`

---

.packit.yaml

Since our upstream repository name differs from the downstream name we should set the `downstream_package_name` [1] config option.
[1]: https://packit.dev/docs/configuration#downstream_package_name

ci/packit: set downstream name

---

cmd/image-builder/main.go

This commit fixes the issue that the auto-detect distro is not visible in the progress message. It also tweaks the order of the message to show:
```
Building manifest for <distro>-<img-type>
```
to be more conistent.
Closes: https://github.com/osbuild/image-builder-cli/issues/121
Note that there is a small tweak needed in the progress library, then this can be properly tested:
```go
func TestManifestIntegrationAutodetectDistro(t *testing.T) {
if testing.Short() {
t.Skip("manifest generation takes a while")
}
if !hasDepsolveDnf() {
t.Skip("no osbuild-depsolve-dnf binary found")
}
restore := main.MockNewRepoRegistry(testrepos.New)
defer restore()
script := `cat - > "$0".stdin`
fakeOsbuildCmd := testutil.MockCommand(t, "osbuild", script)
defer fakeOsbuildCmd.Restore()
restore = …
```

main: fix auto-detected distro that is non-visible, tweak order

---

cmd/image-builder/main.go

This commit fixes the issue that on `CTRL-C` (SIGINT) the progress is not properly cleared.
No test right now as this is hard to test automatically :/
Closes: https://github.com/osbuild/image-builder-cli/issues/123

main: reset the terminal properly on SIGINT

---

cmd/image-builder/export_test.go
cmd/image-builder/main.go
cmd/image-builder/main_test.go

This commit adds a new `-v,--verbose` switch that enables verbose build logging.
Closes: https://github.com/osbuild/image-builder-cli/issues/112

main: add `-v,--verbose` switch that enables verbose build logging

---

cmd/image-builder/describeimg.go
cmd/image-builder/describeimg_test.go

describeimg: typo in describe output

---

cmd/image-builder/main_test.go
go.mod
go.sum

This commit updates the `progress` package to get the latest fixes, most notably
https://github.com/osbuild/bootc-image-builder/pull/820

go.mod: update to get the latest `progress` fixes from `bib`

---

.spellcheck-en-custom.txt
README.md
cmd/image-builder/build.go
cmd/image-builder/export_test.go
cmd/image-builder/main.go
cmd/image-builder/main_test.go
cmd/image-builder/upload.go
cmd/image-builder/upload_test.go
go.mod
go.sum

[edit: one open question is if this PR should also contain a variant of this like `build --uplload-to` so that build/upload can be done in a single call.
This commit adds a new `upload` command that can be used to upload a raw image to the cloud. Currently only AWS is supported but as images adds more clouds to the uploader interfac we can trivially expand more.
Note that this needs https://github.com/osbuild/images/pull/1185

main: add new upload command

---

.spellcheck-en-custom.txt
README.md
cmd/image-builder/filters.go
cmd/image-builder/main.go
cmd/image-builder/main_test.go
cmd/image-builder/manifest.go
cmd/image-builder/repos.go
cmd/image-builder/repos_test.go

This commit adds an `--force-repo` flag that can be used
to replace all the base repositories with a base url to
a repository. This is useful for testing but also dangerous
as it will not do any checks and happily use a fedora-42 repository
for centos-8 depsolving.
This will make the use-case of the koji builder easier and is
also something that the `build` tool in `images` supports.

main: add add `--force-repo` flag

---

.gitignore
cmd/image-builder/main.go
cmd/image-builder/main_test.go
cmd/image-builder/upload.go
cmd/image-builder/upload_test.go

I do not understand what was a point of the error types in the first place when the handling code would just print them. Since strings works great as error values most of the time in Go, it is such easier and cleaner to simply format them correctly when they occur, having them wrapped and let them to bubble up the stack to print them.
This patch fixes that and simplifies the handling code - just return (thus print) any error that occurs, there is no need to do special handling as long as they are correctly formatted and Go error wrapping encourages exactly that.
Additionally, in another commit I am adding `bin/` to the `.gitignore`.

main: simplify upload error handling

---

cmd/image-builder/build.go
cmd/image-builder/main.go
cmd/image-builder/main_test.go
go.mod
go.sum

[draft as this needs https://github.com/osbuild/bootc-image-builder/pull/811 first]
This commit adds support to write a buildlog as part of the build.
By default the buildlog is located in the output dir as e.g.
`centos-9-qcow2-x86_64/centos-9-qcow2-x86_64.buildlog`.

main: add build --with-buildlog

---

.spellcheck-en-custom.txt
README.md
cmd/image-builder/main.go
cmd/image-builder/main_test.go

We had a small meeting about the names for our arguments, we want to be consistent so `basedir` is renamed to `base-dir`. `output` gets renamed to `format`.
Tests are updated, so is the README. Did I miss anything?
This PR replaces the exploratory #99.

main: argument names

---

cmd/image-builder/main.go
cmd/image-builder/main_test.go

This commit adds a "success" message that also contains the output dir when the build finishes.
Thanks to SimonS for suggesting this!

main: show "success" message with output dir when build finishes

---

cmd/image-builder/main.go
cmd/image-builder/main_test.go

This commit skips the arch checks if the experimental "bootstrap" option is used. The main use-case of this option is to bootstrap a foreign architecture so just assume that and skip arch checks when set.
This allows to write:
```
$ IMAGE_BUILDER_EXPERIMENTAL=bootstrap=ghcr.io/mvo5/fedora-buildroot:41 \
./image-builder build --arch=riscv64 minimal-raw --distro=fedora-41
```
and do a riscv64 cross arch build.
[split our from https://github.com/osbuild/image-builder-cli/pull/136 to make cross-build workable]

main: skip arch checks on`IMAGE_BUILDER_EXPERIMENTAL=bootstrap`

---

cmd/image-builder/build.go
cmd/image-builder/main.go
cmd/image-builder/main_test.go
cmd/image-builder/manifest.go
cmd/image-builder/upload_test.go
internal/testutil/testutil.go
internal/testutil/testutil_test.go
test/test_container.py

This commit adds a new `--output-name` flag that will rename the resulting artifact after it was build. All auxillary artifacts like buildlog, sbom etc are also name based on the same basename.
One open question is if this should be "--output-filename" or "--basename".
See also https://github.com/osbuild/images/pull/1039 for how
this could be simpler (especially the fake osbuild).
As a side-effect this will now produce more predictable names by default as well:
```
fedora-42-minimal-raw-zst-x86_64/fedora-42-minimal-raw-zst-x86_64.raw.zst
````

ibcli: add new --output-name flag and predictable default names

---

.github/workflows/pytest.yaml
Containerfile
cmd/image-builder/main.go
cmd/image-builder/main_test.go
cmd/image-builder/manifest.go
go.mod
go.sum
test/test_container.py

This PR enables automatic cross architecture building when `build --arch <foreign>` is passed. It uses the new generalized bootstrap buildroot feature of images.

main: automatically cross build when --arch <foreign> is passed

---

go.mod
go.sum
internal/blueprintload/blueprintload.go
internal/blueprintload/blueprintload_test.go

Add strict checking for toml keys in blueprints. This allows us
to error early if there are unknown keys in a toml blueprint and
helps our users by spotting e.g. typos early.
This is similar to
https://github.com/osbuild/bootc-image-builder/pull/549
(thanks Ondrej!).

blueprintload: enable strict checking for toml

---

go.mod
go.sum
internal/blueprintload/blueprintload.go

This commit moves ibcli over to use the new `osbuild/blueprint` module for better compatibility with the composer and on-prem blueprints.

many: move to use the new github.com/osbuild/blueprint module

---

cmd/image-builder/export_test.go
cmd/image-builder/main.go
cmd/image-builder/main_test.go
cmd/image-builder/manifest.go

This commit tweaks the handling of the `--output-name` option so that is a name with the same extension as the image is passed that is just silently ignored. Its a common issue that first time users run:
```console
$ image-builder build --output-name foo.qcow2 qcow2
```
which currently leads to a `foo.qcow2.qcow2`. 
With this commit the expected "foo.qcow2" will appear.

main: tweak handling of --output-name to avoid adding double extensions

---

go.mod
go.sum

This commit pulls in the latest fixes from
https://github.com/osbuild/blueprint/pull/7

go.mod: update to latest version of `github.com/osbuild/blueprint`

---

cmd/image-builder/main.go
cmd/image-builder/manifest.go
test/test_container.py

Allow users to define the seed that's used for manifest generation. Regenerating an image with a given seed leads to the same manifest (provided depsolving does the same).
The seed is normally mostly used to generate random filesystem UUIDs.
This will need a bunch of documentation in a follow up since the use cases are meant to be advanced but it can really speed up multi-type and rebuilds of the same image.
---
Note that this is part of an ongoing effort, with this change users can opt for the same manifests being generated (barring depsolve changes). This stops the invalidation of the `os` pipeline, which contains filesystem UUIDs. This can then, in a followup, lead to us check pointing more; allowing us to re-use more.
Related to #114, probably only really useful after …

main: allow seed setting

---

Makefile
cmd/image-builder/main.go
image-builder.spec

This embeds the version at build time and displays it when passed the --version flag.

main: Add a --version flag to show the build version

---

pkg/progress/progress.go
pkg/progress/progress_test.go

This commit allows controlling the `osbuild --cache-max-size` option. By default it will set the cache to 20GiB but allows this to be controlled by the user.
Thanks to Simon for raising this.
---
Commit imported from https://github.com/osbuild/bootc-image-builder/pull/812

progress: set --cache-max-size in osbuild

---

.github/workflows/check-spec.yaml
image-builder.spec

Add a check which leverages the osbuild/images@check-spec-deps-action action to check that the SPEC files requires at least the minimum versions for dependencies specified by the `osbuild/images`.

GH Action: check the SPEC osbuild/images deps minimum version

---

cmd/image-builder/describeimg.go
go.mod
go.sum

[draft as it needs https://github.com/osbuild/images/pull/1376 first and once that is in we need to drop the "go mod edit -replace"  commit, also we need to think if that should be `partition_table` or `base_partition_table` in the output]
This commit adds the (base) partition table to the `describe-image`
command. It needs https://github.com/osbuild/images/pull/1376
It currently looks like:
```yaml
$ image-builder describe-image qcow2 --distro fedora-41
@WARNING - the output format is not stable yet and may change
distro: fedora-41
...
partition_table:
uuid: D209C89E-EA5E-4FBD-B161-B461CCE297E0
type: gpt
partitions:
- size: 1048576
type: 21686148-6449-6E6F-744E-656564454649
bootable: true
uuid: FAC7F1FB-3E8D-4137-A512-961DE09A5549
- size: 209715200
type: …
```

main: add base partition table to `describe-image`

---

cmd/image-builder/main.go
cmd/image-builder/main_test.go

Leaves behind a compatibility alias.
---
Split out from #177.

main: rename `describe-image` to `describe`

---

cmd/image-builder/main.go
cmd/image-builder/manifest.go
go.mod
go.sum
image-builder.spec

When running `image-builder` warnings are emitted during manifest generation. Depending on the definitions or customizations packages can be excluded from groups which leads to:
```
No match for group package "dracut-config-rescue"
```
Interspersing with normal output. Let's pass along another byte buffer for the warnings from manifest generation to be written into.
Note that this also needs plumbing [1] to land in `images` first.
[1]: https://github.com/osbuild/images/pull/1384
---
Draft until `images` lands since until then everything in here will be RED.

main: eat depsolve warnings

---

README.md
cmd/image-builder/filters.go
cmd/image-builder/main.go
cmd/image-builder/main_test.go
doc/01-usage.md

Rename the `list-images` command to `list`. We don't have `-image(s)` in our other subcommands so this is for consistency.
We keep a `list-images` alias behind for compatibility reasons.
---
Closes #78, name can be discussed but the initial issue didn't garner attention.

main: rename `list-images` to `list` (with alias for the old names)

---

cmd/image-builder/main.go

Other commands such as `manifest`, and `build` auto detect the distribution if none is given. `describe` is the odd one out that requires `--distro`. Let's also autoselect there.

main: `describe` auto-detect distro

---

cmd/image-builder/main.go

The `completion` command doesn't need to be quite so discoverable. Let's have only actual subcommands listed and mention this in (future) documentation instead.

main: hide `completion` command

---

cmd/image-builder/main.go

The describe format has become quite useful, we should list it in the help page.
---
@mvo5 mentioned this in another PR, perhaps together with #190 it'd be nice to have this subcommand listed in `help`.

main: `describe` non-hidden

---

.packit.yaml

Instead of directly releasing to epel-9 we should release into epel-9-next and do manual merges/releases when/if RHEL and/or CentOS catch up with our dependencies.

ci: release into epel-9-next

---

doc/00-installation.md

There should be a link to the package details, not only the reference to the main fedora page.
Is this link a good choice?

doc/00-installation: Add link to package details

---

.github/workflows/go.yaml
cmd/image-builder/main_test.go

This commit fixes the issue that a test blueprint was not converted from json to TOML. This was not caught in CI apparently because our test container misses createrepo_c.

test: fix missing conversion of a test blueprint to toml

---

cmd/image-builder/export_test.go
cmd/image-builder/main.go
cmd/image-builder/main_test.go
cmd/image-builder/manifest.go

This new flag allows to add a file with registration data. This is meant to eventually hold all sort of registrations like ansible or satelite but initially only contains the redhat subscription. Currently only JSON is supported.
It looks like:
```json
{
"redhat": {
"subscription": {
"activation_key": "ak_123",
"organization": "org_123",
"server_url": "server_url_123",
"base_url": "base_url_123",
"insights": true,
"rhc": true,
"proxy": "proxy_123"
}
}
}
```
This is not part of the blueprint (today) because its more ephemeral than the things we usually put into the blueprint.
This allows us to build images that are immediately registered. It also keeps our options open in the future. If we move to a new blueprint format where we support multiple blueprints and also ephemeral data like this …

main: add new `--registrations` options

---

cmd/image-builder/manifest.go

This commit adds error handling for the `f.Close()` errors when we write the SBOM. Errors on close for RW fds are rare but we should handle them so we return the result of `f.Close()` now when returning in sbomWriter(). We still keep the `defer f.Close()` to ensure we do not leak file descriptors when e.g. `io.Copy()` fails. In the "happy" case f is closed without an error and then the defer f.Close() runs and will error with "ErrClosed" but we can ignore that.
An alternative implementaiton might be:
```golang
func sbomWriter(outputDir, filename string, content io.Reader) (err error) {
...
f, err := os.Create(p)
if err != nil {
return err
}
defer func() { err = errors.Join(f.Close(), err) }()
...
return nil
}
```
no super strong opinion here.
Thanks to Flo for finding this issues! …

manifest: handle "close()" errors in sbomWriter()

---

cmd/image-builder/manifest.go

I missed the discussion in https://github.com/osbuild/image-builder-cli/pull/202 therefore I would like to file a counter-proposal. Generally I agree with the resolution, anonymous function is confusing because it builds on a quirky Go language feature, utility functions that issues a warning are not very helpful (who reads warnings) so the final code looks reasonable. There is one snag I do not like.
Calling `Close` twice is just not right, the second call is guaranteed to fail and while it is ignored thanks to `defer`, some warnings might end up in system journal or audit software for no apparent reason. Thus, I would like to suggest a slight change of the approach that is also recommended in the `close(2)` Linux man page - call `Sync` instead. It does the same thing as `Close` when it …

manifest: use Sync instead of Close

---

README.md

This is a small followup for https://github.com/osbuild/image-builder-cli/pull/201 to include information about how to use the new `--registrations` option.

README.md: add a section about adding "registrations"

---

cmd/image-builder/main.go
cmd/image-builder/main_test.go
internal/olog/package.go
internal/olog/proxy.go
internal/olog/var.go
pkg/progress/progress.go
pkg/setup/setup.go
pkg/setup/setup_test.go
pkg/util/util.go

I would like to propose moving away from logrus in the image-builder-cli (and standalone CLI tools from composer and images as well). The library is in maintenance mode for quite a while and I believe it does not provide a good structured logging capabilities and API (log/slog is better) while for console logging it is an overkill. It was primarily designed to be structured logging library with some human-formatting features (Printf...).
Now, for services like crc/composer, I am currently working on replacing logrus with log/slog structured logging library which is part of Go. However, structured logging is not a great fit for CLI applications since its primary purpose is to machine-readable output (JSON) and although text formatters are available in the standard library, it is not best …

refactor: use standard logger instead of logrus

---

cmd/image-builder/main.go
cmd/image-builder/upload.go
cmd/image-builder/upload_test.go

upload: try to auto-detect the upload arch from the filename
This is another convenience feature for the `image-builder upload`
command: when we do not know the target architecture try to
guess it from the filename. This is not perfect but it will
help a lot of users and should be fine until the day we go
and inspect the image.
---
upload: warn the user if no `--arch` flag is passed on upload
This mitigates the issue that a `image-builder upload` command
currently does not know the target architecture of the image
it uploads.
---
upload: default to boot-mode `uefi-preferred` when unset
When using `image-builder upload --to=aws` we do not know
the bootmode. Ideally we would introspect the image for
the boot mode but that is not trivial right now.
So for now just default to …

image-builder: fix cross-arch uploading

---

doc/01-usage.md

Due to https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/Heading_Elements#avoid_using_multiple_h1_elements_on_one_page metioned in #234 we'll just use a single h1 per document.

doc/01-usage.md: avoid multiple h1 in one document

---

doc/10-faq.md

This references the newly created overview and should fix the missing reference in `01-usage.md`

doc/10-faq.md: add image types documentation

---

README.md

People often forget to mount, we're a bit clearer about this in `bootc-image-builder`; let's make it clear here as well.

readme: mention mount for container

---

.packit.yaml

COPR now supports them, so let's add them! 🚀
/jira-epic HMS-8815
JIRA: [HMS-8829](https://issues.redhat.com/browse/HMS-8829)

packit: enable RHEL 10 builds (HMS-8829)

---

.packit.yaml

With `image-builder` having been released into CentOS we should no longer ship updates for EPEL.

ci/packit: remove EPEL release automation

---

go.mod
go.sum

A replacement directive was still present in the `go.mod`, leading to not installing 0.168 but a variation on 0.167.

deps: fix images 0.168

---

Containerfile
cmd/image-builder/main.go
cmd/image-builder/manifest.go
test/test_container.py

This PR adds support for building bootc based disk images via the new `--bootc-ref` switch. It requires support in the images library.
/jira-epic HMS-8839
JIRA: [HMS-8845](https://issues.redhat.com/browse/HMS-8845)

main: add support disk based bootc images via --bootc-ref  (HMS-8845)

---

Containerfile

Using the container and building with a config.toml with a password will fail with:
```
Building manifest for bootc-based-qcow2
panic: user stage failed cannot generate password: exec: "openssl": executable file not found in $PATH, output:
goroutine 1 [running]:
github.com/osbuild/images/pkg/manifest.(*RawBootcImage).serialize(0xc0002466c0)
/root/go/pkg/mod/github.com/osbuild/images@v0.182.0/pkg/manifest/raw_bootc.go:206 +0x16dc
github.com/osbuild/images/pkg/manifest.Manifest.Serialize({{0xc000907400, 0x8, 0x8}, 0x5, {0x0, 0x0}}, 0xc00042ab40, 0xc00042aba0, 0xc0007d0780, 0xc000635448)
/root/go/pkg/mod/github.com/osbuild/images@v0.182.0/pkg/manifest/manifest.go:191 +0x3e5
```

Install openssl in cli container

---

cmd/image-builder/main.go
go.mod
go.sum

This includes the dropping of `shim-ia32` for Fedora 44 (current rawhide).

deps: update to images 0.191.0

---

cmd/image-builder/upload.go
cmd/image-builder/upload_test.go

Fedora aws images were getting ignored since we renamed the base image type to `server-ami`, this commit adds that type back so that we can build Fedora based aws images.
Fixes https://github.com/osbuild/image-builder-cli/issues/306

cmd/upload: add fedora ami to aws upload (HMS-9388)

---

go.mod
go.sum

This includes the re-enablement of the `s390x` architecture for CentOS `tar` and `qcow2` image types. It also includes the new `pxe-tar` image type. Another is the change in partition table offset for the Fedora `minimal-raw` image type(s). The offset is now 16 MiB instead of 8 MiB.

deps: update to images 0.195.0

---

go.mod
go.sum
image-builder.spec

This most importantly contains the change for a 2 GiB `/boot` partition by default in Fedora.

deps: bump images to 0.202.0

---

.gitignore
cmd/image-builder/main.go
cmd/image-builder/version.go
test/test_container.py

```
Because I have modified my PATH to include a custom osbuild binary, it
is useful to see which osbuild version is being used by image-builder.
After this change, the output looks like this:
$ go run ./cmd/image-builder --version
image-builder:
version: unknown
commit: unknown
dependencies:
images: v0.197.0
osbuild: osbuild 162
```
---
A very tiny refactoring to improve readability of the function.

main: add osbuild version to version command
